In [5]:
import pandas

In [6]:
db = pandas.read_csv("marks.csv")

In [7]:
type(db)

pandas.core.frame.DataFrame

In [8]:
db

Name  Hours  Marks
0  Shivani      5     50
1     Ritu      7     70
2      Tom      8     80
3   Preeti      4     40
4  Prakhar      3     30
5  Pallavi      6     60

In [9]:
# target / dv
y = db['Marks']

In [10]:
y

0    50
1    70
2    80
3    40
4    30
5    60
Name: Marks, dtype: int64

In [11]:
# feature / IV
x = db['Hours']

In [12]:
x.shape

(6,)

In [14]:
type(x)

pandas.core.series.Series

In [15]:
# to chande pandas into numpy
x = x.values

In [16]:
type(x)

numpy.ndarray

In [17]:
x = x.reshape(6,1)

In [19]:
x

array([[5],
       [7],
       [8],
       [4],
       [3],
       [6]], dtype=int64)

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
mind = LinearRegression()

In [22]:
#experience / model / linrear function
# w : weight / coefficient
# model trained
mind.fit(x, y)

LinearRegression()

In [23]:
mind.predict([[2]])

array([20.])

In [24]:
# linear function : y = wx
# w = 10
mind.coef_

array([10.])

In [25]:
# to save model
import joblib

In [27]:
joblib.dump(mind, 'marks.pk1')

['marks.pk1']